version: "3.5"
services:
  sample-app:
    container_name: react-docker
    build:
      context: C:\Users\Admin\Desktop\numer\my-app
      dockerfile: Dockerfile
    volumes:
      - ".:/app"

    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=${NODE_ENV}
    